language: java
notifications:
  slack: serviceulmeu:ZhAFcbRlnPKUo2pnIdy2wpjo

deploy:
  provider: heroku
  api_key:
    secure: 7b7631a8-a6b4-4f37-b1cc-f02428be5a61

services:
  - postgresql

before_install:
  - chmod +x mvnw

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

env:
  - SPRING_DATASOURCE_URL=jdbcpostgres://postgres@localhost/service_finder
  - SPRING_DATASOURCE_USERNAME=postgres
  - SPRING_DATASOURCE_PASSWORD=

before_script:
  - psql -c "CREATE DATABASE service_finder;" -U postgres